// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDC_i4tdqWuUy8pVshNz8c0W27gOK-0lNQ',
    appId: '1:651573037445:web:3d38304addc7b794b09cec',
    messagingSenderId: '651573037445',
    projectId: 'athleteiq-app',
    authDomain: 'athleteiq-app.firebaseapp.com',
    storageBucket: 'athleteiq-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbGLUKKXjUNWPeGeOfGnbFn7gIWcRpOiw',
    appId: '1:651573037445:android:f0bbeb701b20ca19b09cec',
    messagingSenderId: '651573037445',
    projectId: 'athleteiq-app',
    storageBucket: 'athleteiq-app.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJFCH-hkHTbbNsF6u7mFhXVO4b1yQLQ_s',
    appId: '1:651573037445:ios:e22df7ee226f31bcb09cec',
    messagingSenderId: '651573037445',
    projectId: 'athleteiq-app',
    storageBucket: 'athleteiq-app.firebasestorage.app',
    iosBundleId: 'com.athleteiq.app',
  );
}
