import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart';

import 'firebase_options.dart'; // generated by `flutterfire configure` — see guide
import 'theme/app_theme.dart';
import 'services/auth_service.dart';
import 'screens/splash_screen.dart';
import 'screens/sign_in_screen.dart';
import 'screens/sport_selection_screen.dart';
import 'screens/athlete_home_screen.dart';
import 'screens/coach_roster_screen.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  runApp(const AthleteIQApp());
}

class AthleteIQApp extends StatelessWidget {
  const AthleteIQApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'AthleteIQ',
      debugShowCheckedModeBanner: false,
      theme: AppTheme.dark,
      home: const AuthGate(),
      routes: {
        '/sign-in': (_) => const SignInScreen(),
      },
    );
  }
}

/// Section 17 — a coach and an athlete are different journeys, not one
/// generic screen. This gate reads the user's role from Firestore right
/// after auth resolves and sends them down the correct path.
class AuthGate extends StatelessWidget {
  const AuthGate({super.key});

  @override
  Widget build(BuildContext context) {
    final auth = AuthService();

    return StreamBuilder<User?>(
      stream: auth.authStateChanges,
      builder: (context, authSnap) {
        if (authSnap.connectionState == ConnectionState.waiting) {
          return const SplashScreen();
        }
        final user = authSnap.data;
        if (user == null) {
          return const SignInScreen();
        }

        return FutureBuilder<String?>(
          future: auth.getRole(user.uid),
          builder: (context, roleSnap) {
            if (!roleSnap.hasData) return const SplashScreen();

            if (roleSnap.data == 'coach') {
              return CoachRosterScreen(coachUid: user.uid);
            }

            // Athlete: no sport picked yet → onboarding step first.
            // (In production, check athlete.sport via a stream instead of
            // routing blind — this keeps the example short.)
            return _AthleteEntry(athleteUid: user.uid);
          },
        );
      },
    );
  }
}

class _AthleteEntry extends StatelessWidget {
  final String athleteUid;
  const _AthleteEntry({required this.athleteUid});

  @override
  Widget build(BuildContext context) {
    // For a first-run athlete, route to sport selection; the sport
    // selection screen pushes them onward to home once saved.
    // A production build would check `athlete.sport == null` here via
    // FirestoreService().athleteProfile(uid). Kept simple for the guide.
    return AthleteHomeScreen(athleteUid: athleteUid);
  }
}

/// Named routes used by pushReplacementNamed calls in the app.
class AppRoutes {
  static Map<String, WidgetBuilder> forAthlete(String uid) => {
        '/sport-selection': (_) => SportSelectionScreen(athleteUid: uid),
        '/athlete-home': (_) => AthleteHomeScreen(athleteUid: uid),
      };
}
