import '../models/privacy_settings.dart';
import '../models/weekly_report.dart';
import 'privacy_redaction.dart';

/// Plain-text weekly report for share / print workflows.
String formatWeeklyReportText({
  required String athleteName,
  required WeeklyReport report,
  PrivacySettings privacy = PrivacySettings.open,
}) {
  final buf = StringBuffer()
    ..writeln('AthleteIQ — Week in review')
    ..writeln('Athlete: $athleteName')
    ..writeln('Week: ${report.weekLabel}')
    ..writeln('${report.weekStart} → ${report.weekEnd}')
    ..writeln();

  if (report.narrative.isNotEmpty) {
    buf.writeln(report.narrative);
    buf.writeln();
  }

  void row(String label, String value) => buf.writeln('$label: $value');

  row(
    'Sessions completed',
    sharedOrHidden(privacy.trainingLogs, '${report.sessionsCompleted}'),
  );
  row('Check-ins logged', '${report.checkInsLogged}');
  if (privacy.wearableData && report.avgSleepHours != null) {
    row('Avg sleep', '${report.avgSleepHours!.toStringAsFixed(1)} h');
  } else if (!privacy.wearableData) {
    row('Avg sleep', kPrivacyNotShared);
  }
  if (privacy.dailyFatigueCheckIn && report.avgFatigue != null) {
    row('Avg fatigue', '${report.avgFatigue!.toStringAsFixed(1)}/5');
  } else if (!privacy.dailyFatigueCheckIn) {
    row('Avg fatigue', kPrivacyNotShared);
  }
  if (privacy.trainingLogs && report.peakAcwr != null) {
    row('Peak ACWR', report.peakAcwr!.toStringAsFixed(2));
  } else if (!privacy.trainingLogs) {
    row('Peak ACWR', kPrivacyNotShared);
  }
  if (privacy.trainingLogs && report.endAcwr != null) {
    row('ACWR at week end', report.endAcwr!.toStringAsFixed(2));
  } else if (!privacy.trainingLogs) {
    row('ACWR at week end', kPrivacyNotShared);
  }
  row(
    'Total training load',
    sharedOrHidden(
      privacy.trainingLogs,
      report.totalTrainingLoad.toStringAsFixed(0),
    ),
  );
  row('Coach adjustments', '${report.coachAdjustments}');
  if (report.riskLevel != null) row('Risk at week end', report.riskLevel!);
  if (privacy.wearableData && report.recoveryTrend != null) {
    row('Recovery trend', report.recoveryTrend!);
  } else if (!privacy.wearableData) {
    row('Recovery trend', kPrivacyNotShared);
  }

  if (report.dailyLoads.isNotEmpty) {
    buf.writeln();
    buf.writeln('Daily load');
    for (final d in report.dailyLoads) {
      final load = privacy.trainingLogs
          ? d.load.toStringAsFixed(0)
          : kPrivacyNotShared;
      final fatigue =
          privacy.dailyFatigueCheckIn ? '${d.fatigue}' : kPrivacyNotShared;
      buf.writeln('  ${d.date}: load $load, fatigue $fatigue');
    }
  }

  buf.writeln();
  buf.writeln('Generated by AthleteIQ');
  return buf.toString();
}
